<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'Prestashop_emusic');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_1');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', '3BKvwkICrfKG5ZbETE5xGZtRW61HUoRSTL22GinTUdyvSALgr3QGg0TM');
define('_COOKIE_IV_', 'bVBCmwQq');
define('_PS_CREATION_DATE_', '2014-12-06');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'HWYxgL6zObI6UO5WV1VuRcOYY4vvEqJh');
define('_RIJNDAEL_IV_', 'gosR0Qv6wvrgfqUqLNyi6Q==');
